version: "3.7"

services:

  php:
    build: ./.docker/php
    container_name: php
    working_dir: /var/www/php
    volumes:
      - .:/var/www/php:cached
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini:cached